//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Онлайн_Заказы.Бд
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int ЗаказID { get; set; }
        public int КлиентID { get; set; }
        public string Ячейка { get; set; }
        public System.DateTime ДатаЗаказа { get; set; }
        public int Сумма { get; set; }
        public int Количество { get; set; }
        public int Отмена { get; set; }
    
        public virtual Возвраты Возвраты { get; set; }
        public virtual ЗаказаноТоваров ЗаказаноТоваров { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
